### ISSUE TITLE
JSON decode

### ISSUE THREAD

**Issue by tutukaks** [not404/json-arduino#5]
Did this library support JSON decoding. Can I create JSON string from Arduino variables?

**Comment by not404** [comment]
This library takes in a JSON string, and converts into a Key/Value structure. 

The original intent was to be able to control the Arduino by passing in commands via JSON -- for my purposes, the JSON is generated by a Web Application exposed on the Internet.

This tool doesn't create JSON strings from Arduino Variables, and I don't foresee adding support for doing that because it would bloat the code. As the Arduino and its smaller cousins are memory constrained, I would prefer to keep this as "minimal" as possible.

If I had a lot of data to pass back from the Arduino (or a smaller cousin), I would probably try to dump a Struct over the wire, and parse that on the receiving end, which likely is a real computer that is running a custom App.
